# Generated by Django 2.2.1 on 2019-05-05 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_price',
            field=models.ForeignKey(help_text='Venue price relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue', to='parking.LotPrice', verbose_name='venue_price'),
        ),
    ]
