# Generated by Django 2.2.1 on 2019-05-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='public', help_text="Define type of venuepublic venue accessable for non owner userprivate venue are reserved for owner or company user to useIt's help when user is left the car on parking spot and but not take out at the checkout time, and next user have reservation but spot is not available. In such a case owner/manager use spot to manage extra vehicle", max_length=10, verbose_name='venue_type'),
        ),
    ]
