# Generated by Django 2.2.1 on 2019-05-08 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_venue_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(help_text='User reservation relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reservation', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
