# Generated by Django 2.2.1 on 2019-05-09 20:44

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20190508_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'booked'), ('active', 'Active'), ('overdue', 'Overdue'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='pending', help_text='Reservation status', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('building', 'Building'), ('lot', 'Lot'), ('floor', 'Floor')], db_index=True, help_text='Venu CategoryEach venue have specific category', max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Child parent relationshipMPTT relationship to find out parent relation from samemodel object. MPTT provide tree structre view', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parking.Venue', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_price',
            field=models.ForeignKey(help_text='Venue price relationshipEach sellable venue have pricePrice model store that informationIf price relation not available and venue is sellable thenvenue price considered as free', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue', to='parking.LotPrice', verbose_name='venue_price'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='public', help_text="Define type of venuepublic venue accessable for non owner userprivate venue are reserved for owner or company user to useIt's help when user is left the car on parking spot and but not take out at the checkout time, and next user havereservation but spot is not available. In such a caseowner/manager use spot to manage extra vehicle", max_length=10, verbose_name='venue_type'),
        ),
    ]
