# Generated by Django 2.2.1 on 2019-05-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20190509_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reservation amount to be paid', max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='overdue_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late fee charges to be paid', max_digits=10, verbose_name='overdue_amount'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount to be paid for reservation', max_digits=10, verbose_name='total_amount'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount to be paid for reservation', max_digits=10, verbose_name='total_amount'),
        ),
    ]
